# -*- coding: utf-8 -*-
"""NMIZ-training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RiZVQo5_ieH9A8UeTp8PJsiCaes81jCh
"""



# Загрузка модуля pandas
import pandas as pd

# Загрузка файла из облака в colab
import gdown
gdown.download('https://drive.google.com/uc?id=1HneSc4fEx4ayjOU2CwFMzr3pdWW3wK58', None, quiet=True)

data = pd.read_csv('dataset1.csv')

data

# Параметр index_col определяет столбец, который будет использоваться как индекс в таблице
data = pd.read_csv('dataset1.csv', index_col=0)

# Вывод первых 10 строк таблицы
data.head(10)

data.count()

data.describe()

data.nunique()

# перебираю все названия столбцов и для каждого вывожу список уникальных значений
for name, values in data.items():
  print(name, ":", data[name].unique())

# Загрузка файла из облака в colab
import gdown
gdown.download('https://drive.google.com/uc?id=1QAKfworRTLxvwPCvC2w5QU-2D7e0X8QZ', None, quiet=True)

dataCalc = pd.read_csv('calc1.csv')

dataCalc.head(10)

dataCalc.count()

dataCalc.nunique()